### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by DataTables** [comment]
Interesting - thanks for the PR! I need to find some time to go through the various package managers and improve my support for them. I'll come back to this when I do so.

**Comment by kkirsche** [comment]
Also just an FYI there are discussions to move bower to NPM anyway so I wouldn't really plan to support it for ever: bower/bower#1520

**Comment by kkirsche** [comment]
Also their maintainer says they probably won't ever use it: http://stackoverflow.com/questions/24844901/bowers-bower-json-file-version-property

**Comment by DataTables** [comment]
Oops - forgot to update this issue when I did it a while back: f2f35d31f7bb3ee91f14eebbd8efedf88ee5fa66.

**Pull request closed without merging**
