### PR TITLE
Fix typos in code

### PR DESCRIPTION
**Pull request by zoranzoki21**

### CODE REVIEW

**Comment by DataTables** [comment]
Doh - I'm forever doing that one. The [DataTablesSrc repo](/DataTables/DataTablesSrc) is where PRs should be made. Happy to take a PR there or make the changes myself. Whichever suits yourself :)

**Comment by zoranzoki21** [comment]
I will send PR there.

**Comment by zoranzoki21** [comment]
But @DataTables please tell me where is media/js/jquery.dataTables.js placed in repository in which you told me to send PR.

**Comment by zoranzoki21** [comment]
In master at https://github.com/DataTables/DataTablesSrc there are not this typos.

**Comment by DataTables** [comment]
The Src repo is a collection of source files. You'll probably need to grep the repo to find those typos (that's what I'd do anyway :) ).

**Comment by zoranzoki21** [comment]
> You'll probably need to grep the repo to find those typos (that's what I'd do anyway :) ).

Will do, thanks!

**Pull request closed without merging**
