### PR TITLE
non void self-closing tags don't work from jquery 3.5

### PR DESCRIPTION
**Pull request by abiram11**
https://jquery.com/upgrade-guide/3.5/

### CODE REVIEW

**Comment by DataTables** [comment]
Thanks! However, per the [contributing document](https://github.com/DataTables/DataTables/blob/master/Contributing.md) for this repo, this is just a legacy build repo now. All source PRs should be sent to [the DataTablesSrc repo](/DataTables/DataTablesSrc).

Also, `$('<div/>')` will actually work with jQuery 3.5, it's the nested tags that it has problems with - e.g. `$('<div><span/></div>')` and the XHTML self closing tag takes up less bytes, so I've made the decision to continue using them where possible and using no-short tags if nested tags are required. If you are seeing a problem with that somewhere, can you link to a test case please?

DataTables 1.10.21 and its extensions have been tested with jQuery 3.5.1 and are all passing.

**Comment by abiram11** [comment]
Oh, thanks for the info.
Are we certain that '<div/>' still works? From what I see in the source code, htmlPrefilter doesn't do anything in 3.5.1. Maybe I'm looking at the wrong thing?

3.4.1 - https://github.com/jquery/jquery/blob/3.4.1/src/manipulation.js#L240
3.5.1 - https://github.com/jquery/jquery/blob/master/src/manipulation.js#L197

**Comment by DataTables** [comment]
[Quite certain](https://jsfiddle.net/kspgL932/). DataTables is also passing its suit of unit tests.

If it can be shown not to work I will of course change it though!

**Comment by abiram11** [comment]
OK, great. Thanks!

**Pull request closed without merging**
