### PR TITLE
Add JSPM (package manager) compatibility

### PR DESCRIPTION
**Pull request by tshrestha**
- [JSPM](https://github.com/jspm/jspm-cli) is a new package manager and dependency loader.
- Added the `jspm` property to `package.json` which allows _jspm_ to properly install DataTables and its dependencies.
- The DataTablesSrc repository does not have a `package.json` file, therefore the reason for contributing to this repo.
- Also, jspm installs the latest released zip from Github, so this change would have to be merged and released in order for jspm to install DataTables.
- I've also submitted a pull-request to [jspm/registry](https://github.com/jspm/registry) that would add DataTables to the jspm registry.

### CODE REVIEW

**Comment by DataTables** [comment]
Hi,

Thanks for this. I've just been looking through the [JSPM package.json docs](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm) and I'm not sure the changes in the override `jspm` option in the updated JSON are needed are they? JSPM supports `files`, `main` and `dependencies` so isn't the existing file already good to go?

I wonder if we could ask @guybedford for his thought's? (Hi again Guy :-) ).

**Comment by tejens** [comment]
That was my initial understanding as well. But from my experience JSPM does not install the declared dependencies unless the `registry` property is specified. From looking at [package.json specs](https://docs.npmjs.com/files/package.json) , `registry` doesn't seem to be a `package.json` property, therefore the need to include it inside a `jspm` override.

Additionally, a `shim` property (also not part of `package.json`) is also required in order for JSPM to load the dependencies in the correct order.

@guybedford I too like to hear your thoughts/insights on this.

**Comment by guybedford** [comment]
@DataTables hi Allan, great to work on this again! 

* You can include the `registry: jspm` property at the base-level which will allow jspm to read the dependencies, but jspm doesn't support dependency ranges, so it is advisable to use `jquery: *` or the semver range like we have in a special jspm dependencies object like we have here.
* The directories.lib will make other requires easier as the user only needs to do `require('datatables/js/...')` if there were other requires. Although it doesn't seem there are so this isn't too critical.
* The shim config is certainly needed though to set the jQuery dependency.

I'd advise adding a CSS shim like we do for bootstrap (https://github.com/jspm/registry/blob/master/package-overrides/github/twbs/bootstrap%403.1.0.json) as this allow a single require to get everything to work in the browser.

**Comment by DataTables** [comment]
Hi Guy, thanks for your thoughts on this.

> jspm doesn't support dependency ranges

My [package.json file](https://github.com/DataTables/DataTablesSrc/blob/master/descriptors/package.json) uses `"jquery": ">=1.7"` as a dependency. Are you saying that won't work? The problem for me with `jquery:*` is that is isn't true - I know that DataTables requires 1.7 or greater.

> The shim config is certainly needed though to set the jQuery dependency.

Do you have any docs or code you could link me to that show that. I don't quite get that I'm afraid since `jquery` is already in the dependencies list? (probably being a total muppet!)

**Comment by guybedford** [comment]
@DataTables I would still suggest `jquery: '*'` here. I know it is not ideal, but this is entirely due to jQuerys bending of semver. I don't think any users would have reason to install jQuery less than 1.7 in jspm anyway.

`jquery` needs to be duplicated in the shim and dependencies list, because _dependencies_ is the list of package dependencies to be downloaded at install time, while the _shim_ is like doing a `require` - it shows that that specific module is dependent on something. For example, a package could have modules that depend on different dependencies.

Let me know if that makes sense, the best examples to look at are other overrides in the registry like https://github.com/jspm/registry/blob/master/package-overrides/github/lightbox2/lightbox2%402.7.1.json.

**Comment by DataTables** [comment]
What is jQuery's bending of semver? The `>=1.7.0` that I use I thought was valid semver.

> For example, a package could have modules that depend on different dependencies.

I'm totally confused now - sorry, I'm being really thick I'm sure and it might be the terminology that is tripping me up. A module is in a package? And a package is what the package.json file describes - which in this case is my DataTables project? So it could provide multiple modules, each with their own dependency that you can include individually? That's okay, but DataTables doesn't have that, it only has one module and one global dependency. I'm afraid I just don't get what the shim is doing that can't be obtained from the existing information? (sorry - its Friday and I've got a cold so feeling very woolly!)

**Comment by guybedford** [comment]
@DataTables jspm currently doesn't support arbitrary version ranges. This may change over time, but trying to encourage a reduced set of version constraints (basically thinking in terms of locking just major or minor version).

Yes a package is a folder containing module files, which load other modules.

Adding a shim dependency for `dep`, is the equivalent for a global module of having `require('dep')` in the code. That is you need the require statement and the package dependency for things to resolve correctly so that dep is installed (from dependencies) and then required (by shim when loading the module).

**Comment by DataTables** [comment]
Okay - I think I get that now. So the shim is to save jspm from needing to look over the code referred to in the package.json file to find any `require()`'s?

So should I add the following to my package.json file to have it work with jspm:

```js
"jspm": {
	"dependencies": {
		"jquery": "*"
	},
	"registry": "jspm",
	"shim": {
		"js/jquery.dataTables": {
			"deps": ["jquery", "media/css/jquery.dataTables.css!"],
			"exports": "$"
		}
	}
}
```

* Lines 2-4: Override jQuery version to any for JSPM (retaining it at the top level)
* Line 5: Set registry to `jspm`. Presumably this can be done in the `jspm` object to keep everything specific to JSPM in the `jspm` object?
* Line 7: Is this the correct name? Is it the package name? I've based that off the Bootstrap example
* Line 8: require jquery and the DataTables CSS (is `jquery` required here, even although it is in the `dependencies` list? The path is relative to the JS file? Or the package file?
* Line 9: Is this needed? The [documentation](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm) says "exports is detected automatically by the SystemJS loader as any globals written by the script. In most cases this detection will work out correctly."

Thanks!

**Comment by guybedford** [comment]
Sorry for the delay here. Yes - shim is basically requires for globals.

The above looks perfect for jspm configuration. To clarify your questions:

* The registry is mandatory because we allow `registry: npm` as well which gets different treatment.
* The `js/jquery.dataTables` path will only be correct if that is the same as the file path within the package without the .js extension. You may need to set a `directories.lib="media"` option in the package.json so that it takes the package to be the "media" folder, then these paths work out.
* The CSS require needs to be relative to the file itself, as if we were doing a require inside that file - `../css/jquery.dataTables.css!'
* When using CSS requires, it's important to add the CSS plugin as a dependency as it is not in core jspm (yet) (`"css": "^0.1.5"` will do).
* You do need the exports as SystemJS won't detect that the jQuery global was intended as the export for data tables. It only diffs the window object.

Hope that helps.

**Comment by DataTables** [comment]
Super - thanks for the reply!

So I've added the config from above (slightly modified for the paths and to add the css include) [into my package.json file](https://github.com/DataTables/DataTables/blob/master/package.json). What do you think?

**Comment by guybedford** [comment]
Nice, looks great to me! Note that `css` should be in the `dependencies` object and not at the base level.

**Comment by DataTables** [comment]
What a muppet - doh. Fixed now :-)

Is there anything else needed from me here now? When I get a little bit more time I'll make sure that all of my extensions for DataTables will also operate with JSPM.

**Comment by guybedford** [comment]
Nice, `jspm install datatables@master` seems to be working great.

**Comment by DataTables** [comment]
Whoohoo! This must be the longest time a package has been waiting on its author to get it ready for JSPM ever.... (shamefaced)

**Comment by guybedford** [comment]
Haha, yes almost two years! Yours was actually the first or second package I ever configured for jspm and used in demos.

**Comment by DataTables** [comment]
Not sure why I didn't close this issue at the time.

Looks like DataTables is still installing okay with jspm :-). Closing now.

**Pull request closed without merging**
