### PR TITLE
Added a REGEXP selector

### PR DESCRIPTION
**Pull request by tomerigal**
change the LIKE selector to REGEXP only if the regex param is equals to true.

### CODE REVIEW

**Comment by kvvaradha** [comment]
Regex Filter for Serverside Processing and individual columns.

**Comment by DataTables** [comment]
Thanks for the PR. I've never included regex support in the demo script for performance reasons - regex is always going to be slower, however one could argue that it is up to the developer to make that decision themselves...

Are you happy for this to be released under the MIT license?

**Comment by tomerigal** [comment]
Yes it's ok to be released under the MIT license.

**Comment by DataTables** [comment]
Quick update - I'm not going to pull this in for the 1.10.5 release, but rather leave it open for me to consider further and for anyone else interested to +1 it. The standard SSP class is something I very much consider to be a demo and not a "full" piece of software. I _want_ people to modify it to suit their own needs rather than just using it as it is!

**Comment by code-80** [comment]
+1

**Pull request closed without merging**
