### PR TITLE
Displaying Data Table Correctly while fetching/displaying data from ajax

### PR DESCRIPTION
**Pull request by d3xter7-lab**
With the following issue listed on #stackoverflow [https://stackoverflow.com/questions/27873581/datatable-doesnt-work-jquery/68989501](url) , tried to fix the problem of table display, but initially not able to integrate the code in the master repo and file jquery.dataTable.js, if any of you guys know, please do let me know, using this code in the index/js file of the project, the above mentioned bug can be resolved.

### CODE REVIEW

**Comment by AllanJard** [comment]
As shown in [this example](https://datatables.net/examples/basic_init/zero_configuration.html) a `setTimeout` is not required to initialise a DataTable. Please link to a test case showing the issue so we can help to resolve the original issue.

**Comment by d3xter7-lab** [comment]
> As shown in [this example](https://datatables.net/examples/basic_init/zero_configuration.html) a `setTimeout` is not required to initialise a DataTable. Please link to a test case showing the issue so we can help to resolve the original issue.

with the following code 
` $.ajax({
        type:"POST",
        url:"components/entry_tb.php",
        data:{
           'id':event_id,'title':event_title,'body':event_body
        },
        success: function(data){
            $("table[id='tableID'].Display").html(data);
        }
    });`
when I tried to show data on the table, it resulted like this,
original_table_with_issue

but after I have inserted the following code, when the window object is loaded completely, its fixed, as you can see up here when i call the table element with the dataTable() its value gets changed instantly, by just calling it in the console :-
after_calling_the_table

so, as a part, when I called for the same in the index file of my project under setTimeout(), it called the 'table' element/selector with DataTable in a delay of 1100 ms, 

Some references are as follows:- 
[error in dataTables with description.odt](https://github.com/DataTables/DataTables/files/7079700/error.in.dataTables.with.description.odt)
[Issue Encountered for DT Research.odt](https://github.com/DataTables/DataTables/files/7079719/Issue.Encountered.for.DT.Research.odt)



Please see go through the reference & please guide me if I am wrong or misconfigured or misinterpreted something.

**Comment by AllanJard** [comment]
Initialise your DataTable after the HTML has been written to:

```js
$.ajax({
  type: "POST",
  url: "components/entry_tb.php",
  data: { id: event_id, title: event_title, body: event_body },
  success: function (data) {
    $("table[id='tableID'].Display").html(data);
    $("table[id='tableID'].Display").DataTable();
  },
});
```

It sounds like at the moment you might be trying to initialise it outside the `$.ajax` call. Consider what would happen if the network latency was higher on some busy days - 1100mS might not be enough. The best way is to initialise it when it is ready.

If that doesn't help, please link to a test case showing the issue.

**Comment by d3xter7-lab** [comment]
@AllanJard, where table code is written as :-

<?php 
$id=isset($_POST['id'])?$_POST['id']:'No Data';
$title=isset($_POST['title'])?$_POST['title']:'No Data';
$body=isset($_POST['body'])?$_POST['body']:'No Data';
$i=0; 
?>

<table class="Display" id="tableID">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Body</th>
            </tr>
        </thead>
        <tbody>
     <?php 
    for($i;$i<30;$i++){
        echo '<tr id='.$i.'>
               <td id="a'.$id[$i].'">'.$id[$i].'</td>
               <td id="b'.$title[$i].'">'.$title[$i].'</td>
               <td id="c'.$body[$i].'">'.$body[$i].'</td>
               </tr>';
    }
?>
    </tbody>
</table>


(I think I am able to define, if not please tell me as if it is making sense)

**Comment by d3xter7-lab** [comment]
but @AllanJard , can you please describe what is the exact issue with the following and how the defined solution is actually a "solution"
[https://stackoverflow.com/questions/27873581/datatable-doesnt-work-jquery/68989501](url)

**Comment by AllanJard** [comment]
It looks like others have already answered your question on SO. Closing this thread.

**Pull request closed without merging**
