### PR TITLE
Adding MSSQL support to ssp.class

### PR DESCRIPTION
**Pull request by paulobezerr**
There are only one compatibility problem in this class to make
possible use this class with Oracle and SQL Server (2012 or
greater). The problem are LIMIT operation that is the same
syntax in TSQL and Oracle. The second is column delimiter "`".

I added support to pass PDO driver in sql_connect array.
Default is MySQL. Who uses this class must remain working.

$columns param replaced by $driver (PDO::PDO_DRIVER_NAME)
in limit method. It was make possible use multiple databases.

### CODE REVIEW

**Comment by DataTables** [comment]
Looks like a good change - thanks! However, I'm surprised this is all that is needed since the ssp class uses back ticks (`) to escape fields, which is the identifier quoting character in MySQL. MSSQL uses [] and I have no idea what Oracle uses. Perhaps that needs to be abstracted out as well.

**Comment by paulobezerr** [comment]
I see this minutes later. Sorry.

Well, I replaced (`) by ("). But I don't know if works with oracle. I will check it out.

**Comment by paulobezerr** [comment]
Well, like you say, I will remove them.

**Comment by paulobezerr** [comment]
I think better. If some one have a column or table name with special characters this will be a problem. I must find another solution.

**Comment by paulobezerr** [comment]
Sorry for the very long time to adjust the MR.
I do not find a Oracle database to make any tests, so I just change the commit and MR message to describe that I have only added the support to MSSQL not Oracle.

**Comment by DataTables** [comment]
Thanks. The back ticks are often quite useful in MySQL which is why there were there. In SQL Server `[]` can be used instead. Back ticks have also been removed in comments in the above, while I'd prefer them to be retained so it can be formatted as markdown.

To be honest, I'd rather that this demo script in this repo was just that - a simple demo script that would work with a single database. It is meant to be a starting point that can be customised rather than actually being the answer to implementing most server-side processing requests.

Perhaps there should be another repo somewhere that can be used to hold customised versions of this script.

**Comment by paulobezerr** [comment]
No problem. I understand and appreciate the attention.

**Pull request closed without merging**
