### PR TITLE
Component support

### PR DESCRIPTION
**Pull request by holtkamp**
As suggested in https://github.com/DataTables/DataTables/issues/393

### CODE REVIEW

**Comment by nickdietel** [comment]
the repo provided isn't maintained any longer, any way we can get the composer.json updated as suggested?

**Comment by DataTables** [comment]
Adding an external dependency is not something I what to have to do.

**Comment by holtkamp** [comment]
@nickdietel, try this approach for asset management:
https://github.com/francoispluchino/composer-asset-plugin

It supports the bower.json dependencies, so no need for other 'component' stuff. Deleting branch.

**Comment by nickdietel** [comment]
@holtkamp I had a try with the 'composer-asset-plugin'. Indeed it works quite nice, however, there are some drawbacks with this plugin as mentioned by the plugin author. i.e. you need to install the plugin into global prior using it. Please see this post [Use Nodejs for Bower and NPM](https://github.com/francoispluchino/composer-asset-plugin/issues/93)


You might want to check out BowerPHP as an alternative
**BowerPHP**: https://github.com/Bee-Lab/bowerphp

Still I would prefer using the [component-installer](http://robloach.github.io/component-installer/). Actually, having the [extra:component](https://github.com/RobLoach/component-installer#creating-a-component) section included in the composer.json would make the datatables much more useful to everybody.

**Pull request closed without merging**
