### PR TITLE
The change discussed in #653

### PR DESCRIPTION
**Pull request by strang91**
The change discussed in https://github.com/DataTables/DataTables/issues/653

### CODE REVIEW

**Comment by DataTables** [comment]
Thank you for this. As the contributing document notes changes should be committed to the DataTablesSrc repo. Also, the indexes would need to be updated when a row is deleted. I'd also like to check the performance impact of introducing another loop in the initialisation. I suspect it won't be much, but it is worth checking.

**Comment by strang91** [comment]
> As the contributing document notes changes should be committed to the DataTablesSrc repo

I'm kind of new to pull requests and commits. What exactly is the DataTablesSrc rep?

>  Also, the indexes would need to be updated when a row is deleted

The change already has the code that updates the index when the row is deleted.

> I'd also like to check the performance impact of introducing another loop in the initialisation

Which loop in the initialization are you talking about?

**Comment by DataTables** [comment]
[Src repo](https://github.com/DataTables/DataTablesSrc/).

Sorry, yes, I missed the part about the delete indexes - it does look correct. And thats the loop I mentioned. I was reading the code incorrectly.

**Comment by strang91** [comment]
Should I create another pull request on Src Repo?

**Comment by DataTables** [comment]
Yes please, or I can port it over. I can't promise to take it in - but I will certainly look into it.

**Comment by strang91** [comment]
Could you please port it over? I don't know how to create a pull request for multi file changes. Thanks

**Comment by DataTables** [comment]
Yup - I'll leave this one open until I get a chance to do so.

**Comment by strang91** [comment]
Managed to create a new pull request myself. Is now https://github.com/DataTables/DataTablesSrc/pull/57

**Pull request closed without merging**
